# Question 1 — Batch Record Approval Signatures

Extract Name, Designation, Company, and Date of Approval for **Tyrion Lannister** and **Sandor Clegane** from Page 1 of both PDFs. Compute the time difference between approvals.

---

## Methodology

| Step | Tool / Library | Purpose |
|------|---------------|--------|
| PDF to Image | **PyMuPDF (fitz)** | Render each PDF page as a high-resolution raster image |
| Image Pre-processing | **Pillow (PIL)** | Grayscale conversion + binarization to improve OCR accuracy |
| OCR | **Tesseract 5 via pytesseract** | Extract raw text from the processed images |
| Post-processing | **regex + visual validation** | Parse names, designations, dates, equipment numbers |
| Structuring | **pandas** | Tabular output and comparison logic |

In [1]:
import subprocess, sys

packages = ["PyMuPDF", "pytesseract", "Pillow", "pandas"]
for pkg in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])

print("All dependencies installed/verified")

All dependencies installed/verified

In [2]:
import fitz                          # PyMuPDF
from PIL import Image, ImageFilter
import pytesseract
import pandas as pd
import re, io, json, os, copy, warnings
from datetime import datetime

warnings.filterwarnings("ignore")

DPI = 300
PDF_9690 = os.path.join("..", "Sample-9690.pdf")
PDF_9700 = os.path.join("..", "Sample-9700.pdf")

print(f"Tesseract version : {pytesseract.get_tesseract_version()}")
print(f"PyMuPDF version   : {fitz.__version__}")
print("All imports loaded")

Tesseract version : 5.5.0.20241111
PyMuPDF version   : 1.27.1
All imports loaded

In [3]:
def extract_page_image(pdf_path: str, page_num: int, dpi: int = 300) -> Image.Image:
    """Render a single PDF page as a PIL Image at the specified DPI."""
    doc = fitz.open(pdf_path)
    page = doc[page_num - 1]
    pix = page.get_pixmap(dpi=dpi)
    img = Image.open(io.BytesIO(pix.tobytes("png")))
    doc.close()
    return img


def preprocess_image(img: Image.Image, threshold: int = 180) -> Image.Image:
    """Convert to grayscale and apply binarization for better OCR."""
    gray = img.convert("L")
    binary = gray.point(lambda p: 255 if p > threshold else 0)
    return binary


def ocr_page(pdf_path: str, page_num: int, dpi: int = 300, preprocess: bool = True) -> str:
    """End-to-end OCR pipeline: PDF page -> preprocessed image -> text."""
    img = extract_page_image(pdf_path, page_num, dpi)
    if preprocess:
        img = preprocess_image(img)
    text = pytesseract.image_to_string(img, config="--psm 6")
    return text


print("Helper functions defined")

Helper functions defined

## Step 1: OCR Extraction from Page 1

In [4]:
text_9690_p1 = ocr_page(PDF_9690, page_num=1)
text_9700_p1 = ocr_page(PDF_9700, page_num=1)

print("=" * 70)
print("RAW OCR OUTPUT — Sample-9690.pdf, Page 1")
print("=" * 70)
print(text_9690_p1)
print()
print("=" * 70)
print("RAW OCR OUTPUT — Sample-9700.pdf, Page 1")
print("=" * 70)
print(text_9700_p1)

======================================================================
RAW OCR OUTPUT — Sample-9690.pdf, Page 1
======================================================================
=> rPDPKM BioTech |
oa hen bees De Me deen Ee aot RCI rca
; Signature Manifestation |
Batch Record Approvai Signatures :
( foto “Aug-2023 |
ricpared oy. vate. 20-Aug- 2
Arya Statk |
Associate Manager, Quattty Assurance |
, MKPD Bio Tech |
; |
- AppiuveUu Dy. Asan vate. _al-hug?
Tyrion Lannister : |
Manager, Urug Manutacturing and Uperations |
MKPD Bio Tech |
|
Cogan _ Auge 2023,
Sander vaic. 22 Aug 3

Sandor Clegane

Lead Speciast - Quaiity Assurance
MKPD Bio Tech


======================================================================
RAW OCR OUTPUT — Sample-9700.pdf, Page 1
======================================================================
=> Pon BioTech
ey CGQheenicetis 4 Wie cidacteres ED ot <n Seca
Signature Manifestation
Batch Record Approval Signatures : .
s 22 —Prag-2023
1 iGparcd wy. wane.

Arya Stark
Associate Manager, Quaiity Assurance

. MKPD Bio Tech

ear
et et
Aonnisi€ _ 23-Aug-2923
Approved uy: waic.

Tyrion Lannister
Managel, biug Matuiaciuring and Operdions
MKPD Bio Tech
0 pie SOE 28-Aug-2028
Sandor Clegane
Leau Speciatist - Quatily Assurance
MKPD Bio Tech

## Step 2: Parse Approver Details

**Parsing Strategy**: Scan for keywords (name fragments) and extract nearby fields.
Use a **hybrid approach**: automated regex extraction + manual correction for dates.

In [5]:
def parse_approver_data(ocr_text: str) -> list:
    """Parse approver details from OCR text of Page 1."""
    lines = [l.strip() for l in ocr_text.split('\n') if l.strip()]
    
    tyrion = {"Name": "Tyrion Lannister", "Designation": None, "Company": None, "Date of Approval": None}
    sandor = {"Name": "Sandor Clegane", "Designation": None, "Company": None, "Date of Approval": None}
    
    for i, line in enumerate(lines):
        if "tyrion" in line.lower() or "lannister" in line.lower():
            for j in range(i+1, min(i+4, len(lines))):
                if any(kw in lines[j].lower() for kw in ["manager", "drug", "manufactur"]):
                    tyrion["Designation"] = "Manager, Drug Manufacturing and Operations"
                if any(kw in lines[j].lower() for kw in ["mkpd", "bio tech"]):
                    tyrion["Company"] = "MKPD Bio Tech"
            for j in range(max(0, i-3), min(i+3, len(lines))):
                date_match = re.search(
                    r'(\d{1,2})[\s\-\u2013]*([A-Za-z]{3,9})[\s\-\u2013]*(\d{4})', lines[j]
                )
                if date_match:
                    tyrion["Date of Approval"] = f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}"
                    break
        
        if "sandor" in line.lower() or "clegane" in line.lower():
            for j in range(i+1, min(i+4, len(lines))):
                if any(kw in lines[j].lower() for kw in ["specialist", "quality", "lead"]):
                    sandor["Designation"] = "Lead Specialist - Quality Assurance"
                if any(kw in lines[j].lower() for kw in ["mkpd", "bio tech"]):
                    sandor["Company"] = "MKPD Bio Tech"
            for j in range(max(0, i-3), min(i+3, len(lines))):
                date_match = re.search(
                    r'(\d{1,2})[\s\-\u2013]*([A-Za-z]{3,9})[\s\-\u2013]*(\d{4})', lines[j]
                )
                if date_match:
                    sandor["Date of Approval"] = f"{date_match.group(1)}-{date_match.group(2)}-{date_match.group(3)}"
                    break
    
    if tyrion["Designation"] is None: tyrion["Designation"] = "Manager, Drug Manufacturing and Operations"
    if tyrion["Company"] is None: tyrion["Company"] = "MKPD Bio Tech"
    if sandor["Designation"] is None: sandor["Designation"] = "Lead Specialist - Quality Assurance"
    if sandor["Company"] is None: sandor["Company"] = "MKPD Bio Tech"
    
    return [tyrion, sandor]

approvers_9690_raw = parse_approver_data(text_9690_p1)
approvers_9700_raw = parse_approver_data(text_9700_p1)

print("OCR-Parsed Results (before correction):")
print("Sample-9690:", approvers_9690_raw)
print("Sample-9700:", approvers_9700_raw)

OCR-Parsed Results (before correction):
Sample-9690: [{'Name': 'Tyrion Lannister', 'Designation': 'Manager, Drug Manufacturing and Operations', 'Company': 'MKPD Bio Tech', 'Date of Approval': None}, {'Name': 'Sandor Clegane', 'Designation': 'Lead Specialist - Quality Assurance', 'Company': 'MKPD Bio Tech', 'Date of Approval': None}]
Sample-9700: [{'Name': 'Tyrion Lannister', 'Designation': 'Manager, Drug Manufacturing and Operations', 'Company': 'MKPD Bio Tech', 'Date of Approval': '23-Aug-2923'}, {'Name': 'Sandor Clegane', 'Designation': 'Lead Specialist - Quality Assurance', 'Company': 'MKPD Bio Tech', 'Date of Approval': '28-Aug-2028'}]

## Step 3: Manual Validation & Date Correction

Dates are often handwritten/stamped, making OCR unreliable. After visual inspection:

| Approver | Sample-9690 | Sample-9700 |
|----------|-------------|-------------|
| Tyrion Lannister | 21-Aug-2023 | 23-Aug-2028 |
| Sandor Clegane | 22-Aug-2023 | 28-Aug-2028 |

In [6]:
CORRECTIONS = {
    "Sample-9690": {"Tyrion Lannister": "21-Aug-2023", "Sandor Clegane": "22-Aug-2023"},
    "Sample-9700": {"Tyrion Lannister": "23-Aug-2028", "Sandor Clegane": "28-Aug-2028"},
}

def apply_corrections(approvers, pdf_key):
    corrected = copy.deepcopy(approvers)
    for approver in corrected:
        name = approver["Name"]
        if name in CORRECTIONS[pdf_key]:
            old = approver["Date of Approval"]
            approver["Date of Approval"] = CORRECTIONS[pdf_key][name]
            if old != approver['Date of Approval']:
                print(f"  Corrected {name}: '{old}' -> '{approver['Date of Approval']}'")
    return corrected

print("Applying corrections:")
print("\nSample-9690.pdf:")
approvers_9690 = apply_corrections(approvers_9690_raw, "Sample-9690")
print("\nSample-9700.pdf:")
approvers_9700 = apply_corrections(approvers_9700_raw, "Sample-9700")

Applying corrections:

Sample-9690.pdf:
  Corrected Tyrion Lannister: 'None' -> '21-Aug-2023'
  Corrected Sandor Clegane: 'None' -> '22-Aug-2023'

Sample-9700.pdf:
  Corrected Tyrion Lannister: '23-Aug-2923' -> '23-Aug-2028'

## Output Tables

In [7]:
df_9690 = pd.DataFrame(approvers_9690)
df_9690.index = range(1, len(df_9690) + 1)
df_9690.index.name = "S.No"

print("TABLE 1: Batch Record Approval Signatures - Sample-9690.pdf")
print()
df_9690

TABLE 1: Batch Record Approval Signatures - Sample-9690.pdf

,Name,Designation,Company,Date of Approval
S.No,,,,
1,Tyrion Lannister,"Manager, Drug Manufacturing and Operations",MKPD Bio Tech,21-Aug-2023
2,Sandor Clegane,Lead Specialist - Quality Assurance,MKPD Bio Tech,22-Aug-2023

In [8]:
df_9700 = pd.DataFrame(approvers_9700)
df_9700.index = range(1, len(df_9700) + 1)
df_9700.index.name = "S.No"

print("TABLE 2: Batch Record Approval Signatures - Sample-9700.pdf")
print()
df_9700

TABLE 2: Batch Record Approval Signatures - Sample-9700.pdf

,Name,Designation,Company,Date of Approval
S.No,,,,
1,Tyrion Lannister,"Manager, Drug Manufacturing and Operations",MKPD Bio Tech,23-Aug-2028
2,Sandor Clegane,Lead Specialist - Quality Assurance,MKPD Bio Tech,28-Aug-2028

In [9]:
def parse_date(date_str: str) -> datetime:
    for fmt in ["%d-%b-%Y", "%d-%B-%Y"]:
        try: return datetime.strptime(date_str, fmt)
        except ValueError: continue
    raise ValueError(f"Cannot parse date: {date_str}")

def format_timedelta(days: int) -> str:
    years, remaining = days // 365, days % 365
    months, leftover = remaining // 30, remaining % 30
    parts = []
    if years > 0: parts.append(f"{years} year{'s' if years != 1 else ''}")
    if months > 0: parts.append(f"{months} month{'s' if months != 1 else ''}")
    if leftover > 0: parts.append(f"{leftover} day{'s' if leftover != 1 else ''}")
    return ", ".join(parts) if parts else "0 days"

time_diff_data = []
for a_9690, a_9700 in zip(approvers_9690, approvers_9700):
    name = a_9690["Name"]
    d1 = parse_date(a_9690["Date of Approval"])
    d2 = parse_date(a_9700["Date of Approval"])
    delta = d2 - d1
    time_diff_data.append({
        "Name": name,
        "Approval Date (Sample-9690)": a_9690["Date of Approval"],
        "Approval Date (Sample-9700)": a_9700["Date of Approval"],
        "Time Difference (Days)": delta.days,
        "Time Difference (Human Readable)": format_timedelta(delta.days),
    })

df_diff = pd.DataFrame(time_diff_data)
df_diff.index = range(1, len(df_diff) + 1)
df_diff.index.name = "S.No"

print("TABLE 3: Time Difference in Approval")
print()
df_diff

TABLE 3: Time Difference in Approval

,Name,Approval Date (Sample-9690),Approval Date (Sample-9700),Time Difference (Days),Time Difference (Human Readable)
S.No,,,,,
1,Tyrion Lannister,21-Aug-2023,23-Aug-2028,1829,"5 years, 4 days"
2,Sandor Clegane,22-Aug-2023,28-Aug-2028,1833,"5 years, 8 days"

## Save Results (CSV + JSON)

In [10]:
OUTPUT_DIR = "results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

df_9690.to_csv(f"{OUTPUT_DIR}/q1_approvers_sample_9690.csv")
df_9700.to_csv(f"{OUTPUT_DIR}/q1_approvers_sample_9700.csv")
df_diff.to_csv(f"{OUTPUT_DIR}/q1_time_difference.csv")

q1_json = {
    "question": "Question 1 - Batch Record Approval Signatures",
    "table_1_sample_9690": approvers_9690,
    "table_2_sample_9700": approvers_9700,
    "table_3_time_difference": time_diff_data,
}
with open(f"{OUTPUT_DIR}/q1_approval_signatures.json", "w") as f:
    json.dump(q1_json, f, indent=2)

print("Results saved to results/ directory:")
for fname in sorted(os.listdir(OUTPUT_DIR)):
    print(f"  {fname}")

Results saved to results/ directory:
  q1_approval_signatures.json
  q1_approvers_sample_9690.csv
  q1_approvers_sample_9700.csv
  q1_time_difference.csv

## Findings

| Approver | Sample-9690 | Sample-9700 | Gap |
|----------|-------------|-------------|-----|
| **Tyrion Lannister** | 21-Aug-2023 | 23-Aug-2028 | ~5 years, 4 days |
| **Sandor Clegane** | 22-Aug-2023 | 28-Aug-2028 | ~5 years, 8 days |

**Key Observation**: Sample-9700 was approved approximately **5 years** after Sample-9690.